### ISSUE TITLE
Pyhton 39 missing

### ISSUE THREAD

**Issue by forid786** [marcelloc/Unofficial-pfSense-packages#113]
Python39 seems to be missing from the repository. Therefore on pfSense 2.7.0, packages that rely on Python39 do not install such as E2Guardian, and Speedtest-cli.

**Comment by GRB-CONSULTORIA** [comment]
tambe estou com o mesmo problema

**Comment by pablorivara** [comment]
Hi guys,
here a same problem:

_>>> Installing pfSense-pkg-E2guardian5... 
Updating Unofficial repository catalogue...
Unofficial repository is up to date.
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.
pkg-static: e2guardian has a missing dependency: python39
Failed._

If the necessary version of python is installed, does it solve the problem or could it generate some other conflict?

**Comment by 2w-consultoria** [comment]
e2guardian for pfsense 2.7 is not ready yet.

**Comment by IagoCarvalho1** [comment]
Good afternoon, can anyone tell me if there is a solution for this problem?

**Comment by 2w-consultoria** [comment]
> Good afternoon, can anyone tell me if there is a solution for this problem?

https://github.com/marcelloc/Unofficial-pfSense-packages/issues/113#issuecomment-1630773993

**Comment by Dimitrievich** [comment]
hello to all from ukraine

my solution is the following
 enable freeBSD repositories in files
- /usr/local/etc/pkg/repos/pfSense.conf

- /usr/local/etc/pkg/repos/FreeBSD.conf

pkg update
pkg install python39

and then you can install the E2guardian5 package
and all works

**Comment by forid786** [comment]
@Dimitrievich do all the Web pages work for E2guardian after installing python via those repos? As the PHP version has changed.

**Comment by Dimitrievich** [comment]
@forid786
 I tested all tabs
all work fine
if during work or increased load I see errors, I will inform

updates have been needed for a long time. I hope @marcelloc  to make them soon.

**Comment by pablorivara** [comment]
good morning from uruguay
I just tried to install e2g, and surprise!
could be installed without doing anything else. 
Thanks Marcelloc!

**Comment by forid786** [comment]
> @forid786 I tested all tabs all work fine if during work or increased load I see errors, I will inform
> 
> updates have been needed for a long time. I hope @marcelloc to make them soon.

I have the dashboards for E2guardian enabled, I think they were what caused problems on my end. Actually caused a full system crash. I'll clone my pfSense VM and test further in the lab. I'm 100% sure some changes will need to be made as the PHP version has changed in the newer versions of pfSense and pfSense plus. Maybe for now we can workaround without using the dashboard, please let us know how your testing goes under load.

**Comment by pablorivara** [comment]
GM,
Copy/Paste Crash Report

Crash report begins.  Anonymous machine information:

amd64
14.0-CURRENT
FreeBSD 14.0-CURRENT #1 RELENG_2_7_0-n255866-686c8d3c1f0: Wed Jun 28 04:21:19 UTC 2023     root@freebsd:/var/jenkins/workspace/pfSense-CE-snapshots-2_7_0-main/obj/amd64/LwYAddCr/var/jenkins/workspace/pfSense-CE-snapshots-2_7_0-main/sources/FreeBSD-src-REL

Crash report details:

PHP Errors:
[24-Jul-2023 08:43:37 America/Montevideo] PHP Fatal error:  Uncaught TypeError: date(): Argument #2 ($timestamp) must be of type ?int, string given in /usr/local/www/widgets/widgets/e2guardian.widget.php:56
Stack trace:
#0 /usr/local/www/widgets/widgets/e2guardian.widget.php(56): date('H:i', 'time')
#1 /usr/local/www/widgets/widgets/e2guardian.widget.php(76): e2guardian_show_dstats()
#2 /usr/local/www/index.php(428): include('/usr/local/www/...')
#3 {main}
  thrown in /usr/local/www/widgets/widgets/e2guardian.widget.php on line 56
[24-Jul-2023 08:43:48 America/Montevideo] PHP Fatal error:  Uncaught TypeError: date(): Argument #2 ($timestamp) must be of type ?int, string given in /usr/local/www/widgets/widgets/e2guardian.widget.php:56
Stack trace:
#0 /usr/local/www/widgets/widgets/e2guardian.widget.php(56): date('H:i', 'time')
#1 /usr/local/www/widgets/widgets/e2guardian.widget.php(76): e2guardian_show_dstats()
#2 /usr/local/www/index.php(428): include('/usr/local/www/...')
#3 {main}
  thrown in /usr/local/www/widgets/widgets/e2guardian.widget.php on line 56
[24-Jul-2023 08:43:58 America/Montevideo] PHP Fatal error:  Uncaught TypeError: date(): Argument #2 ($timestamp) must be of type ?int, string given in /usr/local/www/widgets/widgets/e2guardian.widget.php:56
Stack trace:
#0 /usr/local/www/widgets/widgets/e2guardian.widget.php(56): date('H:i', 'time')
#1 /usr/local/www/widgets/widgets/e2guardian.widget.php(76): e2guardian_show_dstats()
#2 /usr/local/www/index.php(428): include('/usr/local/www/...')
#3 {main}
  thrown in /usr/local/www/widgets/widgets/e2guardian.widget.php on line 56
[24-Jul-2023 08:53:58 America/Montevideo] PHP Fatal error:  Uncaught TypeError: date(): Argument #2 ($timestamp) must be of type ?int, string given in /usr/local/www/widgets/widgets/e2guardian.widget.php:56
Stack trace:
#0 /usr/local/www/widgets/widgets/e2guardian.widget.php(56): date('H:i', 'time')
#1 /usr/local/www/widgets/widgets/e2guardian.widget.php(76): e2guardian_show_dstats()
#2 /usr/local/www/index.php(428): include('/usr/local/www/...')
#3 {main}
  thrown in /usr/local/www/widgets/widgets/e2guardian.widget.php on line 56



No FreeBSD crash data found.

And widget error

![e2g](https://github.com/marcelloc/Unofficial-pfSense-packages/assets/112877117/c5671265-1179-46af-877b-36328baa99c1)

**Comment by Gleysoncezar** [comment]
Boa tarde pessoal!
Estava com problemas ao tentar instalar o E2guardian, não instalava devido a essa dependência do python. Consegui resolver através do passo a passo neste link da conexTI: 

https://www.conexti.com.br/se-manter-pfsense-26/

Após isso, consegui instalar normalmente o E2guardian. 

Talvez te ajudem também! Abraços!
